export const practitioners = [
  {
    id: '1',
    name: 'Aria Moonstone',
    modality: 'Reiki Master & Energy Healer',
    modalities: ['Reiki', 'Chakra Balancing', 'Aura Cleansing'],
    litScore: 9.4,
    reviews: 47,
    price: 85,
    sessionTypes: ['30 min', '60 min', '90 min'],
    location: 'Los Angeles, CA',
    languages: ['English'],
    verified: true,
    bio: 'Certified Usui Reiki Master with 12 years of practice. I work with clients to clear energetic blockages, balance chakras, and restore harmony in mind, body, and spirit. Sessions are held in a safe, non-judgmental space where deep healing can unfold.',
    specialties: 'Chronic pain, anxiety, spiritual awakening, grief support',
    avatarColor: 'from-violet-400 to-purple-600',
    founder: true,
    fsaEligible: true,
    introVideoUrl: '/mock-intro-aria.mp4',
    w9Status: 'complete',
  },
  {
    id: '2',
    name: 'Kai Sundaram',
    modality: 'Sound Healing & Breathwork',
    modalities: ['Sound Healing', 'Breathwork', 'Tibetan Bowls'],
    litScore: 8.9,
    reviews: 31,
    price: 95,
    sessionTypes: ['60 min', '90 min'],
    location: 'Austin, TX',
    languages: ['English', 'Hindi'],
    verified: true,
    bio: 'Sound healing practitioner trained in Tibetan singing bowls and crystal alchemy. Combining ancient sound therapy with modern breathwork techniques to guide profound states of relaxation and inner clarity.',
    specialties: 'Stress reduction, trauma healing, sleep disorders',
    avatarColor: 'from-blue-400 to-cyan-500',
    founder: true,
    fsaEligible: true,
    introVideoUrl: '/mock-intro-kai.mp4',
    w9Status: 'complete',
  },
  {
    id: '3',
    name: 'Luna Voss',
    modality: 'Human Design Reader',
    modalities: ['Human Design', 'Gene Keys', 'Astrology'],
    litScore: 9.1,
    reviews: 58,
    price: 110,
    sessionTypes: ['60 min', '90 min'],
    location: 'New York, NY',
    languages: ['English', 'German'],
    verified: true,
    bio: 'International Human Design analyst helping individuals decode their energetic blueprint for purpose, relationships, and aligned decision-making. Certified Level 3 Analyst with the IHDS.',
    specialties: 'Career alignment, relationships, life purpose, parenting',
    avatarColor: 'from-indigo-400 to-blue-600',
    founder: false,
    fsaEligible: false,
    introVideoUrl: '/mock-intro-luna.mp4',
    w9Status: 'complete',
  },
  {
    id: '4',
    name: 'Soleil Arcana',
    modality: 'Tarot & Intuitive Counselling',
    modalities: ['Tarot', 'Oracle Cards', 'Intuitive Guidance'],
    litScore: 8.7,
    reviews: 93,
    price: 65,
    sessionTypes: ['30 min', '60 min'],
    location: 'Remote Only',
    languages: ['English', 'French'],
    verified: true,
    bio: 'Intuitive tarot reader and counsellor offering compassionate, practical guidance for life transitions. My readings are grounded, empowering, and never fear-based. Over 500 readings delivered globally.',
    specialties: 'Love & relationships, career crossroads, spiritual growth',
    avatarColor: 'from-amber-400 to-orange-500',
    founder: true,
    fsaEligible: false,
    introVideoUrl: '/mock-intro-soleil.mp4',
    w9Status: 'partial',
  },
  {
    id: '5',
    name: 'River Sage',
    modality: 'Somatic Therapy & Shamanic Healing',
    modalities: ['Somatic Therapy', 'Shamanic Journey', 'Plant Medicine Integration'],
    litScore: 9.7,
    reviews: 22,
    price: 145,
    sessionTypes: ['90 min'],
    location: 'Boulder, CO',
    languages: ['English', 'Spanish'],
    verified: true,
    bio: 'Somatic therapist and trained shamanic practitioner supporting deep nervous system healing and ancestral pattern release. I blend Western body-based modalities with indigenous wisdom traditions.',
    specialties: 'Trauma, PTSD, ancestral healing, plant medicine integration',
    avatarColor: 'from-green-400 to-emerald-600',
    founder: false,
    fsaEligible: true,
    introVideoUrl: '/mock-intro-river.mp4',
    w9Status: 'complete',
  },
  {
    id: '6',
    name: 'Celeste Dharma',
    modality: 'Vedic Astrology & Meditation',
    modalities: ['Vedic Astrology', 'Meditation', 'Mantra'],
    litScore: 8.5,
    reviews: 74,
    price: 80,
    sessionTypes: ['30 min', '60 min', '90 min'],
    location: 'Portland, OR',
    languages: ['English'],
    verified: false,
    bio: 'Vedic astrologer and meditation teacher drawing on 15 years of study in India and the US. I help clients understand their karmic path, timing of life events, and daily practices for spiritual evolution.',
    specialties: 'Life timing, karmic patterns, meditation initiation',
    avatarColor: 'from-rose-400 to-pink-600',
    founder: false,
    fsaEligible: false,
    introVideoUrl: null,
    w9Status: 'none',
  },
  {
    id: '7',
    name: 'Orion Blake',
    modality: 'Akashic Records & Past Life',
    modalities: ['Akashic Records', 'Past Life Regression', 'Soul Contracts'],
    litScore: 9.0,
    reviews: 39,
    price: 120,
    sessionTypes: ['60 min', '90 min'],
    location: 'Sedona, AZ',
    languages: ['English'],
    verified: true,
    bio: 'Certified Akashic Records practitioner and QHHT hypnotherapist. I access the soul\'s record to reveal past life influences, soul contracts, and the deeper why behind repeating patterns.',
    specialties: 'Soul purpose, repeating patterns, relationship karma',
    avatarColor: 'from-purple-400 to-violet-600',
    founder: true,
    fsaEligible: false,
    introVideoUrl: '/mock-intro-orion.mp4',
    w9Status: 'complete',
  },
  {
    id: '8',
    name: 'Maya Krishnan',
    modality: 'Kundalini Yoga & Numerology',
    modalities: ['Kundalini Yoga', 'Numerology', 'Yogic Lifestyle'],
    litScore: 9.2,
    reviews: 61,
    price: 75,
    sessionTypes: ['30 min', '60 min', '90 min'],
    location: 'San Francisco, CA',
    languages: ['English', 'Tamil'],
    verified: true,
    bio: 'Kundalini yoga teacher (KRI certified) and Pythagorean numerologist. My sessions combine movement, breath, and number wisdom to activate your highest potential and align you with your life path.',
    specialties: 'Awakening, energy activation, life path clarity',
    avatarColor: 'from-teal-400 to-cyan-600',
    founder: false,
    fsaEligible: true,
    introVideoUrl: '/mock-intro-maya.mp4',
    w9Status: 'complete',
  },
]

export const founders = {
  totalSlots: 111,
  claimedSlots: 87,
  members: [
    { name: 'Aria Moonstone', role: 'Practitioner', joined: 'Sep 2025', karma: 1240, spotlight: true, quote: 'Lit Up gave my practice a home before the world even knew about it.' },
    { name: 'Kai Sundaram', role: 'Practitioner', joined: 'Sep 2025', karma: 980, spotlight: false, quote: '' },
    { name: 'Gemma R.', role: 'Seeker', joined: 'Sep 2025', karma: 540, spotlight: true, quote: 'Being Founding Member #12 means I get to shape where this goes.' },
    { name: 'Soleil Arcana', role: 'Practitioner', joined: 'Oct 2025', karma: 870, spotlight: false, quote: '' },
    { name: 'Jordan L.', role: 'Seeker', joined: 'Oct 2025', karma: 320, spotlight: false, quote: '' },
    { name: 'Orion Blake', role: 'Practitioner', joined: 'Oct 2025', karma: 760, spotlight: false, quote: '' },
  ],
}

export const currentUser = {
  name: 'Gemma R.',
  role: 'seeker' as 'seeker' | 'practitioner',
  founder: true,
  founderNumber: 12,
  karma: 540,
  membershipTier: 'free' as 'free' | 'plus',
  referralCode: 'GEMMA8R2',
  referralCount: 6,
  referralKarmaEarned: 300,
}

export const communityPosts = [
  {
    id: '1',
    channel: 'home',
    author: 'Lit Up Team',
    authorRole: 'admin',
    founder: false,
    time: '2 hr ago',
    text: 'AMA with Aria Moonstone this Thursday at 6pm ET — bring your questions about energetic boundaries and chakra work! 🔮',
    likes: 84,
    comments: 19,
    pinned: true,
  },
  {
    id: '2',
    channel: 'home',
    author: 'River Sage',
    authorRole: 'practitioner',
    founder: false,
    time: '5 hr ago',
    text: 'Trending this week: somatic grounding techniques for anxious mornings. Sharing my favourite 3-minute practice in the Lounge.',
    likes: 56,
    comments: 8,
    pinned: false,
  },
  {
    id: '3',
    channel: 'advice',
    author: 'Maya T.',
    authorRole: 'seeker',
    founder: false,
    time: '1 hr ago',
    text: 'New to all this — how do I know if Reiki or sound healing is the better starting point for chronic stress?',
    likes: 12,
    comments: 14,
    pinned: false,
  },
  {
    id: '4',
    channel: 'advice',
    author: 'Jordan L.',
    authorRole: 'seeker',
    founder: false,
    time: '3 hr ago',
    text: 'Had my first Vibe Check today and it completely changed how nervous I was about booking a real session. 10/10 recommend starting there.',
    likes: 31,
    comments: 5,
    pinned: false,
  },
  {
    id: '5',
    channel: 'practice',
    author: 'Gemma R.',
    authorRole: 'seeker',
    founder: true,
    time: '4 hr ago',
    text: 'Week 3 of my Practice Lab cohort and I can already feel a shift in how I hold space for myself during meditation. Grateful for this community.',
    likes: 22,
    comments: 6,
    pinned: false,
  },
  {
    id: '6',
    channel: 'lounge',
    author: 'Kai Sundaram',
    authorRole: 'practitioner',
    founder: true,
    time: '6 hr ago',
    text: 'Sharing my updated intake form template for new clients — feel free to remix it for your own practice. Link in comments.',
    likes: 47,
    comments: 11,
    pinned: false,
  },
  {
    id: '7',
    channel: 'lounge',
    author: 'Orion Blake',
    authorRole: 'practitioner',
    founder: true,
    time: '1 day ago',
    text: 'Hit 9.0 LitScore this week after focusing on faster response times to booking requests. Small ops changes really do compound.',
    likes: 38,
    comments: 9,
    pinned: false,
  },
  {
    id: '8',
    channel: 'founders',
    author: 'Lit Up Team',
    authorRole: 'admin',
    founder: false,
    time: '8 hr ago',
    text: 'Founders-only livestream Friday: roadmap preview for Q1 and how your feedback shaped the Karma Engine. Founding 111 only. 🔥',
    likes: 61,
    comments: 22,
    pinned: true,
  },
]

export const missions = [
  {
    id: '1',
    title: 'Sacred Sound for Peace',
    type: 'Community Service',
    typeColor: 'bg-blue-100 text-blue-700',
    stages: ['Planning Circle – Nov 3', 'Recording Sessions – Nov 5–6', 'Public Broadcast – Nov 9'],
    practitioners: 10,
    seekers: 20,
    karma: 400,
    status: 'active',
    progress: 60,
    description: 'A collective sound healing project channelling high-frequency vibrations for global peace and harmony.',
  },
  {
    id: '2',
    title: 'Consciousness Research Circle',
    type: 'Research & Education',
    typeColor: 'bg-purple-100 text-purple-700',
    stages: ['Literature Review – Oct 28', 'Facilitated Sessions – Nov 1–14', 'Report & Publish – Nov 20'],
    practitioners: 5,
    seekers: 15,
    karma: 300,
    status: 'upcoming',
    progress: 0,
    description: 'A collaborative research mission documenting the efficacy of energy healing modalities through structured case studies.',
  },
  {
    id: '3',
    title: 'Community Grief Support',
    type: 'Healing & Energy',
    typeColor: 'bg-rose-100 text-rose-700',
    stages: ['Intake & Matching – Oct 25', 'Weekly Circles – Nov 1–22', 'Closing Ceremony – Nov 24'],
    practitioners: 8,
    seekers: 30,
    karma: 500,
    status: 'active',
    progress: 35,
    description: 'Practitioners and seekers join forces to offer peer-supported grief circles for those navigating profound loss.',
  },
  {
    id: '4',
    title: 'Creative Healing Arts Showcase',
    type: 'Creative Collaboration',
    typeColor: 'bg-amber-100 text-amber-700',
    stages: ['Open Call – Oct 20', 'Creation Period – Oct 22–Nov 8', 'Live Showcase – Nov 12'],
    practitioners: 12,
    seekers: 25,
    karma: 350,
    status: 'completed',
    progress: 100,
    description: 'An open creative collaboration merging healing intentions with art, music, and storytelling into a live digital showcase.',
  },
]

export const testimonials = [
  {
    id: '1',
    practitionerId: '1',
    author: 'Gemma R.',
    rating: 5,
    resonance: 92,
    wouldBook: true,
    text: 'Aria\'s session was unlike anything I\'d experienced before. I felt layers of anxiety just dissolve. I booked again the following week.',
    source: 'lit-up',
    date: '2 weeks ago',
  },
  {
    id: '2',
    practitionerId: '1',
    author: 'Daniel F.',
    rating: 5,
    resonance: 87,
    wouldBook: true,
    text: 'Incredible practitioner. Held such a safe space and her intuition was spot-on about what I needed to work through.',
    source: 'invite',
    date: '1 month ago',
  },
  {
    id: '3',
    practitionerId: '1',
    author: 'Sara M.',
    rating: 4,
    resonance: 78,
    wouldBook: true,
    text: 'Really meaningful session. I appreciated how Aria explained each step. Will definitely return.',
    source: 'lit-up',
    date: '6 weeks ago',
  },
]
